### ISSUE TITLE
PICOL-Generator not available on PICOL website

### ISSUE THREAD

**Issue by Woi** [PicolSigns/PICOL-Generator#2]
Hey,

I get a 404 Not Found error, if I either follow the link of the readme [1] or the link on the PICOL website [2].

Regards
Woi

[1] http://picol.org/icon_generator.php
[2] http://picol.org/picol_icon_generator.php

**Comment by lonjame** [comment]
Hi Marco,

thank you. The generator is made a friend and located on his server. I will contact him.

Best,
Melih

**Comment by Woi** [comment]
Thanks for the quick reply.

**Comment by lonjame** [comment]
It's fixed. I hope I can add new icons to PICOL, soon.

**Comment by Woi** [comment]
Thanks a lot. Should I change the link in the readme?

**Comment by lonjame** [comment]
Hi Woi. I'm not 100% familiar with GitHub, but if you found a broken link it would be great if you change it. Thanks a lot.

**Comment by Woi** [comment]
See pull request #3 The links in the API section of the readme are also broken. But I couldn't figure out how working API links would look like.
