### ISSUE TITLE
Fatal error on PICOL Icon Generator site

### ISSUE THREAD

**Issue by Hipska** [PicolSigns/PICOL-Generator#4]
The icon generator on http://www.picol.org/picol_icon_generator does not work:
> **Fatal error:** Uncaught exception 'ImagickException' with message 'Unrecognized color string' in /www/htdocs/w00a2e04/tools/lab/icongenerator/common/include/generator.php:86 Stack trace: #0 /www/htdocs/w00a2e04/tools/lab/icongenerator/common/include/generator.php(86): Imagick->colorizeimage('#e87b1e', 1) #1 {main} thrown in **/www/htdocs/w00a2e04/tools/lab/icongenerator/common/include/generator.php** on line **86**

**Comment by gubi** [comment]
Ops, sorry!
I'll fix it asap

**Comment by lonjame** [comment]
No problem. I fixed it once but now it's broken again. Maybe my provider changed something.

**Comment by lonjame** [comment]
Hi gubi,
does the following error message mean, that the provider doesn´t support Imagick anymore?
Thank you!

`Fatal error: Uncaught ImagickException: Unrecognized color string in /www/htdocs/w00a2e04/tools/lab/icongenerator/common/include/generator.php:115 Stack trace: #0 /www/htdocs/w00a2e04/tools/lab/icongenerator/common/include/generator.php(115): Imagick->colorizeimage('#000000', 1) #1 {main} thrown in /www/htdocs/w00a2e04/tools/lab/icongenerator/common/include/generator.php on line 11`

**Comment by lonjame** [comment]
Found the issue. Changed line 115 in generator.php from
`$first -> colorizeImage("#" . $color, 1);`
to
`$first -> colorizeImage("#" . $color, 1, true);`

**Comment by gubi** [comment]
Yes, the application needs [ImageMagick](http://php.net/manual/en/book.imagick.php) installed on the machine.
Anyway, the [`colorizeImage`](http://php.net/manual/en/imagick.colorizeimage.php) method should expects only two parameters.
Are you sure that works?

I would find the time for an update...

**Comment by lonjame** [comment]
Hi I changed the parameters I mentioned before and now it works on http://picol.org/picol_icon_generator.php <http://picol.org/picol_icon_generator.php>

**Comment by lonjame** [comment]
Hi I changed the parameters I mentioned before and now it works on http://picol.org/picol_icon_generator.php

**Comment by gubi** [comment]
:+1:
